<?php
return array(
    'Synapse\Module'                 	=> __DIR__ . '/Module.php',
    'Synapse\Controller\Restful\AbstractRestfulController' => __DIR__ . '/src/Synapse/Controller/Restful/AbstractRestfulController.php',
    'Synapse\Controller\Restful\LoginController' 	=> __DIR__ . '/src/Synapse/Controller/Restful/LoginController.php',
    'Synapse\Controller\Restful\RegisterController' 	=> __DIR__ . '/src/Synapse/Controller/Restful/RegisterController.php',
    'Synapse\Controller\Restful\SessionRestController' 	=> __DIR__ . '/src/Synapse/Controller/Restful/SessionRestController.php',
    'Synapse\Controller\AbstractActionController' => __DIR__ . '/src/Synapse/Controller/AbstractActionController.php',
    'Synapse\Controller\IndexController' 	=> __DIR__ . '/src/Synapse/Controller/IndexController.php',
    'Synapse\Model\Service\AbstractService'  => __DIR__ . '/src/Synapse/Model/AbstractService.php',
    'Synapse\Model\AbstractTable'     	=> __DIR__ . '/src/Synapse/Model/AbstractTable.php',
    'Synapse\Model\Table\CustomerTable'    	=> __DIR__ . '/src/Synapse/Model/Table/CustomerTable.php',
    'Synapse\Model\Table\AuditTable'    	=> __DIR__ . '/src/Synapse/Model/Table/AuditTable.php',
    'Synapse\Model\Table\DeviceTable'    	=> __DIR__ . '/src/Synapse/Model/Table/DeviceTable.php',
    'Synapse\Model\Table\PackageTable'    	=> __DIR__ . '/src/Synapse/Model/Table/PackageTable.php',
    'Synapse\Model\Table\PaymentTable'    	=> __DIR__ . '/src/Synapse/Model/Table/PaymentTable.php',
    'Synapse\Model\Table\Entity\Audit'    	=> __DIR__ . '/src/Synapse/Model/Entity/Audit.php',
    'Synapse\Model\Table\Entity\Customer'    	=> __DIR__ . '/src/Synapse/Model/Entity/Customer.php',
    'Synapse\Model\Table\Entity\RecurlyAccount' => __DIR__ . '/src/Synapse/Model/Entity/RecurlyAccount.php',
    'Synapse\Model\Table\Entity\Device'    	=> __DIR__ . '/src/Synapse/Model/Entity/Device.php',
    'Synapse\Model\Table\Filter\AuditFilter'    	=> __DIR__ . '/src/Synapse/Model/Filter/AuditFilter.php',
    'Synapse\Model\Table\Filter\CustomerFilter'    	=> __DIR__ . '/src/Synapse/Model/Filter/CustomerFilter.php',
    'Synapse\Model\Table\Filter\DeviceFilter'    	=> __DIR__ . '/src/Synapse/Model/Filter/DeviceFilter.php',
    'Synapse\Authentication\Storage\AuthStorage'    	=> __DIR__ . '/src/Synapse/Authentication/Storage/AuthStorage.php',
);
